include:
  - board: nice_nano/nrf52840/zmk
    shield: defiant_left nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano/nrf52840/zmk
    shield: defiant_right nice_view
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
