name: Build

on:
  push:
    paths:
      - 'firmware/**'
  pull_request:
    paths:
      - 'firmware/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: firmware/config
      build_matrix_path: firmware/build.yaml
