name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-v1:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # config_path must be a direct child of the repo root -- see config-v1/west.yml
      config_path: config-v1
      build_matrix_path: config-v1/build.yaml
      archive_name: defiant-v1

  build-v2:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config-v2
      build_matrix_path: config-v2/build.yaml
      archive_name: defiant-v2
